### ISSUE TITLE
[Question] Assigning hard constraints

### ISSUE THREAD

**Issue by infinity77** [uqfoundation/mystic#107]
Hello,

I apologize in advance for the possibly stupid question. I’ve just started using Mystic and I found a great deal of examples dealing with nonlinear constraints, although pretty much all of them apply penalties (using quadratic_inequality), such as:

import mystic as my

@my.penalty.quadratic_inequality(constraint, kwds=dict(hotel=h))
def penalty(x):
    return 0.0

However, I would like to impose a hard constraint, not a penalty, using a method defined in a class (which can’t be expressed as a formula, so I can’t use mystic.symbolic and generate_constraint, generate_solvers, simplify etc..).

Could you please let me know what is the recommended approach in this case?

Thank you in advance for your time.

Andrea.

**Comment by mmckerns** [comment]
@infinity77: So, you have numerical constraints that can be expressed as a function.  Ok.

If you want to impose a box constraint, then do that (i.e. with `SetStrictRange` or similar).  However, if you don't have a box constraint, and you want to impose a functional constraint, you have a few choices:
1) build a function `c` that maps `x` to `x'` as `x' = c(x)`.    Here's a simple one:
`x = np.round(x)` -- this maps real `x` to integer `x'`.  Or build a function of two
variables that sets the second variable to two times the first, and returns both variables.
See also "examples2/boolean.py".
2) code an equation or equations, as if you were coding a penalty (i.e. soft constraint),
then use `as_constraint` to convert from a soft to hard constraint. There are other converters as well.

**Comment by infinity77** [comment]
Hi Mike,

Thank you so much for your answer. I’m not 100% clear still, although I might be able to find a working solution. It appears to me that when using as_constraint, for example, a nonlinear solver is run inside the main nonlinear solver (to satisfy the constraints?).

If that’s the case I might have to re-evaluate my switch from penalties to constraints as my objective function (and those constraints too) are kind of expensive to evaluate...

Thank you again for your suggestions. Please feel free to correct any of the statements above if I have misunderstood something.

Andrea.

**Comment by mmckerns** [comment]
@infinity77: That is correct.  Basically, if you have an analytical function that can map coordinate space to solution space, using a constraint from `mystic` is faster then just about anything (because it searches over a reduced solution space).  However, if you don't have an analytical function, then `mystic` can build a numerical mapping (i.e. a nested optimization that is executed each iteration) to satisfy the constraints.  The numerical mapping can become very expensive, but in some cases, you don't care about the speed as it can provide a solution while other methods struggle to solve the problem.

Let me know if you would like some specific examples, or otherwise.  If not, then please close this ticket.

**Comment by infinity77** [comment]
Hi Mike,

    thank you for your helpful response. I believe I will leave the "constraints" as penalties as they are right now, there is no way to express the constraints in any analytical way for the problem I am working on. But I'll keep in mind your explanations.

Andrea.

**Comment by infinity77** [comment]
> @infinity77: So, you have numerical constraints that can be expressed as a function. Ok.
> 
> If you want to impose a box constraint, then do that (i.e. with `SetStrictRange` or similar). However, if you don't have a box constraint, and you want to impose a functional constraint, you have a few choices:
> 
> 1. build a function `c` that maps `x` to `x'` as `x' = c(x)`.    Here's a simple one:
>    `x = np.round(x)` -- this maps real `x` to integer `x'`.  Or build a function of two
>    variables that sets the second variable to two times the first, and returns both variables.
>    See also "examples2/boolean.py".
> 2. code an equation or equations, as if you were coding a penalty (i.e. soft constraint),
>    then use `as_constraint` to convert from a soft to hard constraint. There are other converters as well.

Hi Mike,

my apologies to come back with yet another stupid question, but I was trying to find a way to use the alternative 1 above that you suggested. One of my penalties is simply an inequality relation between two variables and should not involve the calculation of the objective function. It is something like this:

X1 - 3*a*X2 <= 0

Where a is a (fixed) parameter, and X1 and X2 are two of my (4) parameters that characterize my objective function. I have been reading your suggestion 1 a few times but I am still unclear how I can build a function `c` that maps `x` to `x'` as `x' = c(x)` in this specific case - assuming it's possible.

Do you have any suggestion on how to proceed? Thank you in advance for your help.

Andrea.

**Comment by mmckerns** [comment]
Something like this:
```
>>> import mystic.symbolic as ms>>> equation = 'x1 - 3*a*x2 <= 0'
>>> eqn = ms.simplify(equation, locals=dict(a=1), all=True)
>>> print(eqn)
x1 <= 3*x2
>>> c = ms.generate_constraint(ms.generate_solvers(eqn, nvars=3))
>>> c([1,2,3])
[1, 2, 3]
>>> c([0,100,-100])
[0, -300.0, -100]
```
