### ISSUE TITLE
Client side crashing

### ISSUE THREAD

**Issue by MacWhinny** [uqfoundation/mystic#108]
Hi, i've been on two servers, one being my own when after i've eaten the inventory upgrade cake i've gone and clicked the O in your inventory and every single time it's crashed the client and happened to everyone else. 
It was on the ATM3 remix modpack version 1.0.1 with sponge recommended build. 

Dunno if this is a known issue but i've had to ban it on my server

**Comment by mmckerns** [comment]
@MacWhinny: These are not the droids you are looking for.  Sorry, wrong github.
