### ISSUE TITLE
simplify and constraints solver fail for exponent-only equation

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/mystic#117]
Fails for python 2.7 (confirmed) and most recent mystic dev version.
```
>>> equations = """
... 2**(-x0) + 2**(1-x1) + (2**-x0)*(2**-x1) + 1e-17 <= 1e-16
... """
>>> from mystic.symbolic import generate_constraint, generate_solvers, simplify
>>> try:
...   eq = simplify(equations)
... except Exception as e:
...   print(e)
... 
maximum recursion depth exceeded while calling a Python object
>>> 
>>> cf = generate_constraint(generate_solvers(equations))
>>> cf([1,1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/mystic/coupler.py", line 75, in func
    return f(inner(x, *args, **kwds), *argz, **kwdz)
  File "<string>", line 4, in solver_4401808488
  File "<string>", line 1
SyntaxError: can't assign to operator
>>> 
```

**Comment by mmckerns** [comment]
Note that a change of the equation to remove the powers works as expected.
```
>>> equations = '''
... 2*(-x0) + 2*(1-x1) + (2*-x0)*(2*-x1) + 1e-17 <= 1e-16
... '''
>>> 
>>> from mystic.symbolic import generate_constraint, generate_solvers, simplify
>>> simplify(equations)
'x0 <= (2.0*x1 - 2.0)/(4.0*x1 - 2.0)\nx1 > 0.500000000000000'
>>> 
>>> cf = generate_constraint(generate_solvers(simplify(equations)))
>>> cf([1.,1.])
[166799986198907.78, 0.4999999999999985]
>>> from mystic.symbolic import generate_conditions, generate_penalty
>>> pf = generate_penalty(generate_conditions(equations), k=1e3)
>>> pf([166799986198907.78, 0.4999999999999985])
0.0
>>> 
```

**Comment by nelsoncsc** [comment]
This works for me when using the version 0.3.3. Earlier versions don't work.

**Comment by mmckerns** [comment]
@nelsoncsc: can you clarify?  You are saying that mystic-0.3.3 can process: 
```
equations = """
... 2**(-x0) + 2**(1-x1) + (2**-x0)*(2**-x1) + 1e-17 <= 1e-16
... """
```
but earlier versions fail -- is that correct?  This would also say that somewhere around 0.3.4, the ability to process this equation broke.

**Comment by nelsoncsc** [comment]
Hi @mmckerns , I did not test version 0.3.2.  Only version 0.3.3 and newer versions.
It did work for 0.3.3 but I confirm it is broken for newer versions.

**Comment by mmckerns** [comment]
@nelsoncsc: This appears to work for me now, upon a quick check.
Works for python-2.7, sympy-1.0, mystic-0.3.7.dev0.
Works for python-3.6, sympy-1.6.2, mystic-0.3.7.dev0.
Works for python-3.7, sympy-1.1.1, mystic-0.3.7.dev0.
Works for python-3.8, sympy-1.4, mystic-0.3.7.dev0.

What versions are you seeing the failure in?

**Comment by nelsoncsc** [comment]
Hi @mmckerns ,
I tried python-3.6.9, sympy-1.6.2, mystic-0.3.6

**Comment by mmckerns** [comment]
Can you try the current (master) version of mystic?  If it works, then I'll close this.  If not, then this needs more investigation.

**Comment by nelsoncsc** [comment]
I tried current version and it has the same problem.

**Comment by mmckerns** [comment]
So it appears that you and I both tested with python-3.6.9, sympy-1.6.2, mystic-0.3.7.dev0, and we get different outcomes...  Hmmm...

**Comment by nelsoncsc** [comment]
Hi @mmckerns , it appears it was something broken in my environment, sorry. You can close the issue.
Thank you for solving the problem.
