### ISSUE TITLE
How to stop an optimization 

### ISSUE THREAD

**Issue by infinity77** [uqfoundation/mystic#118]
Hello,

I posted the same question on StackOverflow but I guess this is a better place to ask...

I have a fairly large and complex Python application to which I recently added the ability to perform nonlinear optimization using Mystic.
The optimization runs in a separate thread from the main (GUI) thread. I am naively using the fmin_powell or diffev to run the optimization.

Since the evaluation of the objective function can be lengthy, the user has the ability to click on a “stop” button and stop the simulation.

That said, I haven’t found an intelligent way to actually stop the optimization thread, as there seems not be to stop the fmin_powell or diffev functions. I don’t need to be able to stop the current function evaluation in the middle of the simulation, I would also be happy to wait until the current function evaluation is finished before halting the optimization.

Does anyone know if this is actually possible?

Thank you in advance for your help.

Andrea.

**Comment by mmckerns** [comment]
Answered here: https://stackoverflow.com/a/57282241/2379433.
If that works for you, please close the issue.  Feel free to continue the thread here or on SO, but no need to post to both.

**Comment by infinity77** [comment]
thank you Mike, I’ll comment on SO
