### ISSUE TITLE
3rd party solver & penalties

### ISSUE THREAD

**Issue by infinity77** [uqfoundation/mystic#129]
#Hello,

First of all I’d like to thank you for developing Mystic, it’s an amazing library. 

While I like the existing solvers, I have a bunch of others I’d wish to try: I’ve seen the example at https://github.com/uqfoundation/mystic/blob/master/examples2/constrained_scipy.py, but as far as I can see it uses constraints, while most of my use cases are with penalties. Do you know if it is possible to plug in a 3rd party solver and use penalties instead of constraints? 

My apologies if an example already exists, I wasn’t able to find it.

Thank you.

**Comment by mmckerns** [comment]
@infinity77:  I don't have an example of using penalties on a third-party solver - however, it should also work much in the same way as with the constraints.  So you'll just make a cost function that includes the penalty in an additive fashion, something like this: 
`cost = lambda x:  f(x) + penalty(x)`.

I do have ~10 new optimizers that I'll be rolling out this year, some of the solvers from `scipy.optimize` and some other specialty ones.  Let me know (or close) if this answers your question.

**Comment by infinity77** [comment]
Hi Mike,

Thank you for the super fast answer. I’ll try your suggestion and report back if I misunderstood something.
I’m very curious to take a look at the new solvers - I also work a lot with different ones. Not sure if it’s helpful or not or if you’ve seen it before, but I did some analysis on quite a few nonlinear solvers a while back: http://infinity77.net/global_optimization/multidimensional.html

**Comment by mmckerns** [comment]
Thanks for the link.  I've been looking for more benchmark problems.  One of the issues I always had with benchmark studies is that they typically test against the default settings of the solver... and people generally don't use the default settings for a solver, but rather a tuned solver.  So, I've alway thought that benchmark studies should test solvers by testing across all the possible settings for the solver.  Anyway, it's a nice study.  Maybe you might have an idea for how one would compare solver capabilities with something like mystic, where the goal is solver flexibility and customization.

**Comment by infinity77** [comment]
@mmckerns, in the kind of exercise I have done it is very very difficult to tune all the solvers for 180+ different test functions. Even if it were possible, for some algorithms you have to know the theory behind - and sometimes quite well- to tune the solvers appropriately: think genetic algorithms, for example, with crossover/mutation rates and all other esoteric parameters that a person not versed in those subtleties (and sometimes in a rush to get results) doesn’t know how to handle.
Testing for flexibility and customization is a much tougher exercise in my opinion: as far as I know there are no frameworks that allow you to apply constraints/penalties as seamlessly as Mystic does, and very few that allow fine control to solver iterations as Mystic does. I also very much appreciate that SciPy is not a dependency, as SciPy has become a hundreds-of-MB-10-seconds-import-time monster. The only thing I miss inside Mystic  is having more solvers to test, but as you said they are in the plan and apparently it’s not that difficult to hook a 3rd party solver into it.
I think it boils down to your definition of “flexibility” and “customization”.

**Comment by mmckerns** [comment]
@infinity77: yeah, I know it's a bit of a deficiency in mystic to have as few solvers as I have, but in my own experience, other solvers aren't really needed -- if you care about solving the problem, as opposed to efficiency.  Other solvers will be more efficient in the cases they are built for... but with mystic's ability to customize any solver for a given problem, the choice of solver is far less relevant than the choice of constraint, penalty, or convergence criterion.  With regard to testing, I use mystic for multiply nested optimizations, so think optimization to tune hyper parameters of estimators in machine learning.  I don't see why one couldn't do exactly the same thing for the solver itself.  One of mystic's UQ capabilities is determination of model error under uncertainty -- meaning what is the expected difference between what is predicted and "truth", where the model (in this case, the solver) has uncertainty in the outcomes.  I use this to test robustness and accuracy of an estimator against data it's not seen.  I believe this would also be a good study to test the robustness of a solver.  I've never seen a study like that before, and have been interested in doing something like that for a while.  But time constraints, you know...  that's the same reason I've had the 10+ other solvers in a research branch for about a decade... and that we all haven't written/pushed the code that we want.  Anyway, I appreciate your comments.
