### ISSUE TITLE
ModuleNotFoundError: No module named 'mystic.models'

### ISSUE THREAD

**Issue by radmaker** [uqfoundation/mystic#139]
I was trying to run example02.py from 'examples' which minimizes Rosenbrock's Function with Nelder-Mead. However there occurred a ModuleNotFoundError. After copying the 'models' subdir into the 'mystic' subdir it worked.
I was also trying to change the import statement to:

from models import rosen

This leads to the same error, this time in 'poly.py'.

**Comment by mmckerns** [comment]
How was this built?  Can you share mystic version number and python version?
I'm not able to reproduce in my environment, but maybe I could with more information.

**Comment by mmckerns** [comment]
One might experience something like you are if one didn't install the code (using `python setup.py install` or `pip install mystic`), but instead downloaded the source tarball and tried to run it in place.

I'm going to assume that's what happened.  However, if it's not, then please do reopen this issue and provide more information.
