### ISSUE TITLE
GET ERROR WHEN RUN THE SVR ALGORITHM

### ISSUE THREAD

**Issue by monasabeti** [uqfoundation/mystic#161]
@Colin Beran
this is my code which i copied from your page:
![Capture](https://user-images.githubusercontent.com/43193011/144821843-aa28afb6-2ed8-4189-ae3a-11e7f739ddfe.PNG)

and i face with this error:
![Capture](https://user-images.githubusercontent.com/43193011/144822105-009d10c9-3203-460e-bfee-8a04b6e18eab.PNG)

I TRY ALL THE SOULUTION on the web, but i have not solved it yet;/

**Comment by mmckerns** [comment]
This doesn't seem to be relevant for `mystic`.  The issue appears to be with regard to `sklearn`.

**Comment by monasabeti** [comment]
so how can i solve the problem anyway?

**Comment by mmckerns** [comment]
Your data is the wrong shape, reshape it as is suggested in the traceback.
