### ISSUE TITLE
Python 3.9 pip installation issue with numpy

### ISSUE THREAD

**Issue by asim-pointivo** [uqfoundation/mystic#164]
It appears that, with Python `3.9`, if I already have `numpy-1.22.2` (latest version as of 17th Feb 2020) in my conda enviornment, then when installing `mystic`, pip will try to downgrade `numpy` to version `1.19.5`. I looked at the `setup.py` and it appears that we are only restricting numpy version to be lesser than `1.20.0` with Python `3.6`; see here https://github.com/uqfoundation/mystic/blob/e6ee20e5b751c60d9c8a5444c868ad175623af99/setup.py#L430. The `setup.py` would indicate that on Python `3.9`, it should not try to downgrade `numpy`. 

I was not able to figure this issue out, but I think I might have some clue as to what might be happening. I downloaded the wheel for `mystic` from here https://pypi.org/project/mystic/0.3.8/#files and took a look at `metadata.json` and `METADATA` files; both mention "numpy (<1.20.0,>=1.0)" as requirements. I believe we have a single `wheel` for all python versions, we might need to build multiple wheels for different python versions.

**Comment by mmckerns** [comment]
@asim-pointivo: your reasoning may be correct.  I likely built the wheel with python3.6.

A new release is imminent, and 3.6 is being deprecated.  So, I believe this issue should go away with a new wheel.  I believe I should also change my build procedure to use the latest stable supported version to build wheels, as opposed to the oldest.

**Comment by mmckerns** [comment]
related?: https://github.com/uqfoundation/pathos/issues/222

**Comment by mmckerns** [comment]
should be fixed (by #171). Reopen if it's not.
