### ISSUE TITLE
Tests failures

### ISSUE THREAD

**Issue by infinity77** [uqfoundation/mystic#186]
Hello Mike,

first, I would like to thank you for maintaining this wonderful library. I have a bit of an issue when running the unit tests, I get something like 121 failures plus a bunch of collection errors. I am attaching a log file with the output of this command:

```
python -B -m pytest -s -vv
```

Run directly inside the mystic folder in site-packages (although I get the same result if I run it from another folder). This is on Windows 10 64 bit, Python 3.9.10 (from WinPython), NumPy 1.21.5+mkl, mystic 0.4.0 from PyPI, PyTest 6.2.5.

I am sure I am missing something fundamental here, any suggestion is much appreciated...

Thank you.

Andrea.

Log: 
[mystic_test_log.txt](https://github.com/uqfoundation/mystic/files/9990675/mystic_test_log.txt)

**Comment by mmckerns** [comment]
@infinity77: I generally don't run the test suite with `pytest`, so I'm not sure what the expected performance of it is, to be honest.  As my many of my codes heavily utilize parallel computing, I've found (at least historically) that `pytest` mishandles `multiprocessing`... so I've instead used a hand-rolled test suite.  Essentially, `mystic.tests` has a `__main__.py` so you can run it with `python -m mystic.tests`.  It'd be nice to use `pytest`, as it's a standard though.

It seems that when run with `pytest` many of the tests are failing with the same very basic error (i.e. something is missing, undefined, etc). Does this answer your question, or are you requesting that the tests pass with `pytest`?

**Comment by mmckerns** [comment]
Andrea, no worries.  You can see the build testing here: https://app.travis-ci.com/github/uqfoundation/mystic.  You will note from the builds that I don't test on windows, so it would be great to hear whether you encounter any test failures or not.  If you see an AssertionError, however, try running the test a second time... infrequently an optimization doesn't converge within tolerance and then one of the tests may then fail.

**Comment by infinity77** [comment]
Everything works as advertised, no tests failures, no matter how many times I run them. Thank you @mmckerns 😊
