### ISSUE TITLE
Mystic for prediction in social systems?

### ISSUE THREAD

**Issue by datnamer** [uqfoundation/mystic#72]
Hello,

I noticed some material on mystic that described its use for physical systems. I wonder what you think of of mystic for estimating uncertainty/prediction in complex social systems?

**Comment by mmckerns** [comment]
Like what?  In the abstract, the answer is "yes".  `mystic` is problem agnostic, so it shouldn't be an issue.  Maybe you can better describe the typical problem, and we can see if there's anything missing.  What I mean is, are there large systems of linear equations, is there labelled data, …?

**Comment by mmckerns** [comment]
I've started using `mystic` as a constrained nonlinear optimization engine for machine learning, and there are definitely some problems with complex social systems in typically classification problems.  As it seems there's no further input, then I'll take that my answer of "yes" was good enough.
