### ISSUE TITLE
Contribution to mystic

### ISSUE THREAD

**Issue by arita37** [uqfoundation/mystic#81]
Hello,

Am working on large scale optimization projects and starting doing similar dev than mystic,
monitoring of the optimization process. 

Just wondering how external people can join this project and how the dev. part is done.

Kind regards

**Comment by mmckerns** [comment]
If you would like to contribute, then feel free to make a pull request.  If you don't know what to do, there are issues that you could pick up, both on this site (https://github.com/uqfoundation/mystic/issues) and older issues here (http://trac.mystic.cacr.caltech.edu/project/mystic/query.html).  Or, you could email me  to get a start.
