### ISSUE TITLE
import mystic.monitors as _m  AttributeError: 'module' object has no attribute 'monitors'

### ISSUE THREAD

**Issue by arita37** [uqfoundation/mystic#82]
After installing mystic from GIT sources, we have the following message  when importing:

```
 pip install git+https://github.com/uqfoundation/mystic.git --upgrade --no-deps

import mystic

import mystic.monitors as _m
AttributeError: 'module' object has no attribute 'monitors

'
```

**Comment by mmckerns** [comment]
@arita37: I don't get this error.  Can you tell me more about how you installed `mystic`? What is your OS and version of python?  Also, is this your full traceback?

**Comment by arita37** [comment]
Python 2.7
Win 64bits
mystic-0.2a2.dev0-py2.7.egg-info

Yes, it cannot find the sub-package.

Mystic is a good project, it sounds like it aims mainly for internal use 
for you/ your team needs,
rather a way to work with the community.

Maybe, you want to keep methodology for yourself.
So, it might be hard to contribute

**Comment by mmckerns** [comment]
Why did you not install any of the dependencies?

**Comment by arita37** [comment]
Already installed before

You can see this is linked to mystic sub-package
NOTHING to with any dependencies.....

**Comment by mmckerns** [comment]
Yeah, I'm just trying to confirm that you don't have a bad install -- something that errored out.

I asked you to `import mystic` as above, and confirm what you see, can you do that?  I could observe this behavior if I were in a directory that had a importable folder (or a file) called `mystic` -- so it could be a `PATH` issue, or it could be an install issue.  That's really the only two possibilities.  The `__init__.py` file for `mystic` includes `monitors`, so I don't expect it to be something other than an install or an `PATH` issue.

**Comment by arita37** [comment]
I reinstalled the whole after deleting the files.
It works now.
It seems some files were corrupted.
Thanks for your check/help.
