### ISSUE TITLE
readthedocs.io project

### ISSUE THREAD

**Issue by wulmer** [uqfoundation/mystic#97]
Hi, I noticed that there was no public HTML documentation available for `mystic` (or is there anywhere?) so I decided to set up and configure a new readthedocs.io project. Please @mmckerns, take over the project at https://readthedocs.org/projects/mystic/, you should already be an admin for this project and feel free to remove me from the project.

I stumbled upon your project once again today when I was looking for ways to define termination criteria for optimization processes. Nice [`termination`](https://mystic.readthedocs.io/en/latest/mystic.html#module-mystic.termination) module!

**Comment by mmckerns** [comment]
@wulmer: Thanks for doing that.  Setting up HTML docs at readthedocs.org was actually on my agenda for the next release, and I have been going through the docs and standardizing them so they use standard `sphinx` formatting. (see: https://github.com/uqfoundation/mystic/commit/a5599f0f5a51b6980f97ab0e41a35f6b42356a25, and similar).

**Comment by mmckerns** [comment]
Webhooks are in, and @wulmer I popped you off the project.  Thanks for the kick in the butt. Docs still need some TLC in several sections, but that will happen.
